name: Node.js Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - uses: pnpm/action-setup@v1
        with:
          version: 4.11.1
      - run: pnpm recursive test

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - uses: pnpm/action-setup@v1
        with:
          version: 4.11.1
      - run: pnpm recursive publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
      - uses: pnpm/action-setup@v1
        with:
          version: 4.11.1
      - run: pnpm recursive publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
